<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 *
 * @author    Hibrido - 2023  
 */
-->

<div class="banner-slider">
    <?php $banners = $block->getBannerImages(); ?>
    <?php foreach ($banners as $banner): ?>
        <a href="<?= $banner['url']; ?>">
            <img src="<?= $banner['image']; ?>"
            alt="<?= $banner['alt']; ?>"/>
            <span><?= $banner['title']; ?></span>
        </a>
    <?php endforeach; ?>
</div>
