<div class="block-grid">
    <span class="title-grid">Conheça nossos diferenciais</span>
    <div class="content-grid">
        <?php $banners = $block->getBannerImages(); ?>
        <?php foreach ($banners as $banner): ?>
            <div class="item-grid">
                <a href="<?php echo $banner['url']; ?>">
                    <img src="<?php echo $banner['image']; ?>"
                    alt="<?php echo $banner['alt']; ?>"/>
                    <div class="info-item-grid">
                        <span class="title-item-grid"><?php echo $banner['title']; ?></span>
                        <span class="description-grid"><?php echo $banner['description']; ?></span>
                        <button class="button-grid">Saiba mais</button>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
