<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 *
 * @author    Hibrido - 2023  
 */
-->

<div class="block-howitworks">
    <span class="title-howitworks"><?=__('How it works'); ?></span>
    <div class="content-howitworks">
        <?php $banners = $block->getBannerImages(); ?>
        <?php foreach ($banners as $banner): ?>
            <div class="item-howitworks">
                <a href="<?= $banner['url']; ?>">
                    <img src="<?= $banner['image']; ?>"
                    alt="<?= $banner['alt']; ?>"/>
                    <span class="title-item-howitworks"><?= $banner['title']; ?></span>
                    <span class="description-howitworks"><?= $banner['description']; ?></span>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
